### ISSUE TITLE
[Feature] integration with vidir

### ISSUE THREAD

**Issue by FlyingWombat** [alexherbo2/explore.kak#2]
What do you think about integrating with [vidir]( http://joeyh.name/code/moreutils/)?
It's a UNIX shell program that edits a directory's contents (`mv`, `cp`) using a text editor.

**Comment by alexherbo2** [comment]
How do you see that integration.

**Comment by alexherbo2** [comment]
By the way, I wrote [Bulk].  It is more powerful and general purpose.  It can be used to edit the contents of a directory – like [vidir], but has no concept of files internally, only arguments.

[Bulk]: https://github.com/alexherbo2/bulk
[vidir]: https://joeyh.name/blog/entry/unix_tools_vidir/

**Comment by FlyingWombat** [comment]
> By the way, I wrote [Bulk](https://github.com/alexherbo2/bulk).

Oh, cool! Bulk would work.  

Basically I see the integration as:  
Press `e` to edit the directory using vidir or Bulk.
Have an option to use the program user's preference (vidir or bulk).  
Ideally, Bulk/vidir would be run in a buffer on the same client as it was called.

I'll admit, I don't know how this would be implemented (I'm a new kak user).  
And, the feature would be less useful if Bulk/vidir couldn't connect to an existing Kakoune instance -- then it would just be a shortcut to opening a new terminal and running Bulk/vidir in the current directory.

This isn't a high priority; just an idea.  
Would this be better as a separate plugin?

**Comment by alexherbo2** [comment]
Yep.

**Comment by alexherbo2** [comment]
@FlyingWombat I want to keep it at exploring, not managing.

**Comment by alexherbo2** [comment]
If you want external application support, you might want to try [Connect].

[Connect]: https://github.com/alexherbo2/connect.kak
